// Mock catalog. seller_id / store_name are the store relationship — every
// product belongs to exactly one store (see `stores` below), matched by
// seller_id === Store.id.

export type Subcategory = { id: string; name: string };

export type Category = {
  id: string;
  name: string;
  tagline: string;
  subcategories: Subcategory[];
};

export type ProductBadge = "organic" | "cold_sale" | "bestseller";

export type Product = {
  id: string;
  name: string;
  categoryId: string;
  brandId: string;
  price: number;
  compareAtPrice?: number;
  unit: string;
  description: string;
  image: string;
  tag?: string;
  badge?: ProductBadge;
  rating: number;
  reviewCount: number;
  color?: "black" | "blue" | "brown" | "gray" | "green" | "red";
  inStock: boolean;
  /** FK into `stores` — the store selling this product. */
  seller_id: string;
  /** Denormalized copy of the owning store's name, kept in sync with it. */
  store_name: string;
  /** FK into the owning Category's `subcategories` — set by vendor-side product management. */
  subcategoryId?: string;
  /** Vendor-tracked unit count, independent of the `inStock` flag. */
  stockQty?: number;
  /** Unique within the vendor's own catalog (PRD 6.2). */
  sku?: string;
  barcode?: string;
  /** PRD 6.2: min must be <= max, which must not exceed available stock. */
  minOrderQty?: number;
  maxOrderQty?: number;
  /**
   * Vendor-side visibility flag, distinct from `inStock` (PRD 6.2: "Disabling
   * a product hides it from customers immediately but keeps it in past order
   * records"). Only consumed by the vendor panel's own product list — the
   * customer catalog reads `productsByStore()` directly and is unaffected.
   */
  enabled?: boolean;
  /**
   * Vendor-managed image gallery. `image` stays the single source customer
   * components read (product-card, PDP, cart, etc.) — when a vendor manages
   * a gallery, `images[0]` is kept in sync with `image` so those unchanged
   * consumers still show the right "main" photo.
   */
  images?: string[];
};

export type StoreCategory = { id: string; name: string };

export const storeCategories: StoreCategory[] = [
  { id: "grocery", name: "Grocery" },
  { id: "fruits-vegetables", name: "Fruits & Vegetables" },
  { id: "dairy", name: "Dairy" },
  { id: "bakery", name: "Bakery" },
  { id: "food-beverages", name: "Food & Beverages" },
  { id: "pharmacy", name: "Pharmacy" },
  { id: "beauty-personal-care", name: "Beauty & Personal Care" },
  { id: "baby-care", name: "Baby Care" },
  { id: "pet-supplies", name: "Pet Supplies" },
  { id: "electronics", name: "Electronics" },
  { id: "fashion", name: "Fashion" },
  { id: "home-kitchen", name: "Home & Kitchen" },
  { id: "stationery", name: "Stationery" },
  { id: "organic-products", name: "Organic Products" },
];

export type Store = {
  id: string;
  slug: string;
  name: string;
  tagline: string;
  categoryId: string;
  description: string;
  address: string;
  rating: number;
  /** Distance from the customer, in km — shown instead of a delivery-time claim. */
  distanceKm: number;
  /** Order subtotal (USD) above which delivery is free. */
  freeDeliveryThreshold: number;
  isOpen: boolean;
  isFeatured?: boolean;
  /** Theme color for the generated cover gradient + logo initials badge. */
  accent: string;
  /** Real assets, if ever added — falls back to the generated accent look. */
  logo?: string;
  coverImage?: string;
};

export const stores: Store[] = [
  {
    id: "freshmart-grocery",
    slug: "freshmart-grocery",
    name: "FreshMart Grocery",
    tagline: "Fresh groceries delivered daily",
    categoryId: "grocery",
    description:
      "Everyday groceries and pantry staples, delivered fast from the neighborhood store.",
    address: "12 Main St N, Brampton ON",
    rating: 4.6,
    distanceKm: 2,
    freeDeliveryThreshold: 30,
    isOpen: true,
    isFeatured: true,
    accent: "#4d8b3f",
    logo: "/store-logos/freshmart-grocery.svg",
  },
  {
    id: "green-basket",
    slug: "green-basket",
    name: "Green Basket",
    tagline: "Farm-fresh fruits & vegetables",
    categoryId: "fruits-vegetables",
    description: "Farm-direct fruits and vegetables, picked at peak and delivered the same day.",
    address: "88 Queen St E, Brampton ON",
    rating: 4.7,
    distanceKm: 3,
    freeDeliveryThreshold: 30,
    isOpen: true,
    isFeatured: true,
    accent: "#4d8b3f",
    logo: "/store-logos/green-basket.svg",
  },
  {
    id: "daily-dairy",
    slug: "daily-dairy",
    name: "Daily Dairy",
    tagline: "Fresh milk, paneer & dairy essentials",
    categoryId: "dairy",
    description: "Cold-chain fresh milk, paneer, and dairy essentials from local farms.",
    address: "45 Kennedy Rd S, Brampton ON",
    rating: 4.8,
    distanceKm: 2,
    freeDeliveryThreshold: 25,
    isOpen: true,
    isFeatured: true,
    accent: "#3b6fa0",
    logo: "/store-logos/daily-dairy.svg",
  },
  {
    id: "bake-bliss",
    slug: "bake-bliss",
    name: "Bake Bliss",
    tagline: "Freshly baked breads, cakes & pastries",
    categoryId: "bakery",
    description: "Naturally leavened breads, cakes, and pastries baked fresh every morning.",
    address: "210 Bovaird Dr W, Brampton ON",
    rating: 4.8,
    distanceKm: 5,
    freeDeliveryThreshold: 35,
    isOpen: true,
    isFeatured: true,
    accent: "#8a5a3b",
    logo: "/store-logos/bake-bliss.svg",
  },
  {
    id: "spice-hub",
    slug: "spice-hub",
    name: "Spice Hub",
    tagline: "Premium spices and everyday grocery essentials",
    categoryId: "grocery",
    description: "Premium spices, oils, and daily grocery essentials for every kitchen.",
    address: "150 Bramalea Rd, Brampton ON",
    rating: 4.5,
    distanceKm: 7,
    freeDeliveryThreshold: 50,
    isOpen: true,
    accent: "#c94a3a",
    logo: "/store-logos/spice-hub.svg",
  },
  {
    id: "organic-harvest",
    slug: "organic-harvest",
    name: "Organic Harvest",
    tagline: "Healthy organic foods and grains",
    categoryId: "organic-products",
    description: "Certified organic grains, honey, and pantry staples grown without shortcuts.",
    address: "77 Mavis Rd, Mississauga ON",
    rating: 4.6,
    distanceKm: 12,
    freeDeliveryThreshold: 60,
    isOpen: false,
    accent: "#4d8b3f",
    logo: "/store-logos/organic-harvest.svg",
  },
  {
    id: "medicare-pharmacy",
    slug: "medicare-pharmacy",
    name: "MediCare Pharmacy",
    tagline: "Medicines and healthcare essentials",
    categoryId: "pharmacy",
    description: "Medicines and healthcare essentials, dispensed and delivered around the clock.",
    address: "320 Steeles Ave W, Brampton ON",
    rating: 4.7,
    distanceKm: 4,
    freeDeliveryThreshold: 40,
    isOpen: true,
    accent: "#c94a3a",
    logo: "/store-logos/medicare-pharmacy.svg",
  },
  {
    id: "smart-electronics",
    slug: "smart-electronics",
    name: "Smart Electronics",
    tagline: "Latest gadgets and home electronics",
    categoryId: "electronics",
    description: "The latest gadgets, accessories, and home electronics, delivered to your door.",
    address: "500 Hurontario St, Mississauga ON",
    rating: 4.3,
    distanceKm: 10,
    freeDeliveryThreshold: 75,
    isOpen: true,
    accent: "#3b6fa0",
    logo: "/store-logos/smart-electronics.svg",
  },
  {
    id: "fashion-avenue",
    slug: "fashion-avenue",
    name: "Fashion Avenue",
    tagline: "Trending clothing and accessories",
    categoryId: "fashion",
    description: "Trending clothing and accessories for every season.",
    address: "25 Peel Centre Dr, Brampton ON",
    rating: 4.4,
    distanceKm: 8,
    freeDeliveryThreshold: 60,
    isOpen: false,
    accent: "#8a8a8a",
    logo: "/store-logos/fashion-avenue.svg",
  },
  {
    id: "home-essentials",
    slug: "home-essentials",
    name: "Home Essentials",
    tagline: "Everything your home needs",
    categoryId: "home-kitchen",
    description: "Everything your home needs — from kitchen basics to everyday upkeep.",
    address: "180 Sandalwood Pkwy E, Brampton ON",
    rating: 4.5,
    distanceKm: 6,
    freeDeliveryThreshold: 50,
    isOpen: true,
    accent: "#8a5a3b",
    logo: "/store-logos/home-essentials.svg",
  },
  {
    id: "pet-paradise",
    slug: "pet-paradise",
    name: "Pet Paradise",
    tagline: "Food and accessories for pets",
    categoryId: "pet-supplies",
    description: "Food, treats, and accessories to keep every pet happy and healthy.",
    address: "60 Dixie Rd, Mississauga ON",
    rating: 4.6,
    distanceKm: 9,
    freeDeliveryThreshold: 50,
    isOpen: true,
    accent: "#c94a3a",
    logo: "/store-logos/pet-paradise.svg",
  },
  {
    id: "baby-care-world",
    slug: "baby-care-world",
    name: "Baby Care World",
    tagline: "Trusted products for babies and moms",
    categoryId: "baby-care",
    description: "Trusted, gentle products for babies and moms, delivered with care.",
    address: "140 Chinguacousy Rd, Brampton ON",
    rating: 4.7,
    distanceKm: 5,
    freeDeliveryThreshold: 40,
    isOpen: true,
    accent: "#3b6fa0",
    logo: "/store-logos/baby-care-world.svg",
  },
  {
    id: "beauty-bloom",
    slug: "beauty-bloom",
    name: "Beauty Bloom",
    tagline: "Cosmetics and skincare products",
    categoryId: "beauty-personal-care",
    description: "Cosmetics and skincare picks for every routine, curated and delivered fast.",
    address: "95 Eglinton Ave W, Mississauga ON",
    rating: 4.5,
    distanceKm: 11,
    freeDeliveryThreshold: 55,
    isOpen: true,
    accent: "#8a5a3b",
    logo: "/store-logos/beauty-bloom.svg",
  },
  {
    id: "stationery-point",
    slug: "stationery-point",
    name: "Stationery Point",
    tagline: "School and office supplies",
    categoryId: "stationery",
    description: "School and office supplies, stocked and ready whenever you need them.",
    address: "30 McLaughlin Rd, Brampton ON",
    rating: 4.4,
    distanceKm: 7,
    freeDeliveryThreshold: 45,
    isOpen: false,
    accent: "#111111",
    logo: "/store-logos/stationery-point.svg",
  },
  {
    id: "quickbites-cafe",
    slug: "quickbites-cafe",
    name: "QuickBites Cafe",
    tagline: "Snacks, beverages and ready-to-eat meals",
    categoryId: "food-beverages",
    description: "Snacks, beverages, and ready-to-eat meals for whenever hunger strikes.",
    address: "270 Airport Rd, Mississauga ON",
    rating: 4.6,
    distanceKm: 6,
    freeDeliveryThreshold: 35,
    isOpen: true,
    isFeatured: true,
    accent: "#c94a3a",
  },
];

export const categories: Category[] = [
  {
    id: "fruits-veg",
    name: "Fruits & Vegetables",
    tagline: "Picked at peak",
    subcategories: [
      { id: "cuts-sprouts", name: "Cuts & Sprouts" },
      { id: "exotic", name: "Exotic Fruits & Veggies" },
      { id: "fresh-fruits", name: "Fresh Fruits" },
      { id: "fresh-veg", name: "Fresh Vegetables" },
      { id: "herbs", name: "Herbs & Seasonings" },
      { id: "packaged-produce", name: "Packaged Produce" },
      { id: "party-trays", name: "Party Trays" },
    ],
  },
  {
    id: "meats-seafood",
    name: "Meats & Seafood",
    tagline: "Fresh cuts daily",
    subcategories: [
      { id: "beef", name: "Beef Products" },
      { id: "chicken-turkey", name: "Chicken and Turkey Products" },
      { id: "fish", name: "Fish Varieties" },
      { id: "lamb", name: "Lamb Products" },
      { id: "processed-red-meat", name: "Processed Red Meat Products" },
      { id: "seafood", name: "Seafood" },
    ],
  },
  {
    id: "breakfast-dairy",
    name: "Breakfast & Dairy",
    tagline: "Cold-chain fresh",
    subcategories: [
      { id: "breads-cereal", name: "Breads and Cereal Products" },
      { id: "breakfast-cereals-bars", name: "Breakfast Cereals and Bars" },
      { id: "butter-margarine", name: "Butter & Margarine" },
      { id: "cereals-granolas", name: "Cereals and Granolas" },
      { id: "cheese", name: "Cheese Varieties" },
      { id: "dairy-processing", name: "Dairy Processing Products" },
      { id: "eggs", name: "Eggs and Egg Products" },
      { id: "fresh-dairy", name: "Fresh Dairy Products" },
    ],
  },
  {
    id: "breads-bakery",
    name: "Breads & Bakery",
    tagline: "Baked fresh",
    subcategories: [
      { id: "pastries-rolls", name: "Bakery Pastries and Rolls" },
      { id: "fresh-bread", name: "Fresh Bread Varieties" },
      { id: "glazed-filled", name: "Glazed and Filled Products" },
      { id: "gluten-free", name: "Gluten-Free Alternatives" },
      { id: "organic-breads", name: "Organic and Natural Breads" },
      { id: "pizza-flatbreads", name: "Pizza and Flatbreads" },
      { id: "sandwich-wraps", name: "Sandwich Bread and Wraps" },
      { id: "sweets-pastry", name: "Sweets and Pastry Products" },
    ],
  },
  {
    id: "beverages",
    name: "Beverages",
    tagline: "Sip & refresh",
    subcategories: [
      { id: "drink-boxes", name: "Drink Boxes & Pouches" },
      { id: "coffee", name: "Coffee" },
      { id: "craft-beer", name: "Craft Beer" },
      { id: "milk-plant", name: "Milk & Plant-Based Milk" },
      { id: "soda-pop", name: "Soda & Pop" },
      { id: "sparkling-water", name: "Sparkling Water" },
    ],
  },
  { id: "frozen", name: "Frozen Foods", tagline: "Freezer picks", subcategories: [] },
  { id: "biscuits-snacks", name: "Biscuits & Snacks", tagline: "Clean labels", subcategories: [] },
  {
    id: "grocery-staples",
    name: "Grocery & Staples",
    tagline: "Everyday essentials",
    subcategories: [],
  },
  { id: "household", name: "Household Needs", tagline: "Home & clean", subcategories: [] },
  { id: "healthcare", name: "Healthcare", tagline: "Wellness picks", subcategories: [] },
  { id: "baby", name: "Baby & Pregnancy", tagline: "Little ones", subcategories: [] },
  { id: "electronics", name: "Electronics", tagline: "Gadgets & tech", subcategories: [] },
  { id: "fashion", name: "Fashion", tagline: "Wear it well", subcategories: [] },
  { id: "pet-supplies", name: "Pet Supplies", tagline: "For your pet", subcategories: [] },
  { id: "beauty", name: "Beauty & Personal Care", tagline: "Look after you", subcategories: [] },
  { id: "stationery", name: "Stationery", tagline: "Desk & school", subcategories: [] },
];

export const brands = [
  { id: "harvest", name: "Harvest Co", count: 5 },
  { id: "daily", name: "Daily Fresh", count: 3 },
  { id: "orchard", name: "Orchard Lane", count: 3 },
  { id: "millhouse", name: "Millhouse", count: 3 },
  { id: "kitchen", name: "Slow Kitchen", count: 3 },
  { id: "aashirvaad", name: "Aashirvaad", count: 1 },
  { id: "daawat", name: "Daawat", count: 1 },
  { id: "amul", name: "Amul", count: 1 },
  { id: "vadilal", name: "Vadilal", count: 1 },
  { id: "britannia", name: "Britannia", count: 2 },
  { id: "hellmanns", name: "Hellmann's", count: 1 },
  { id: "modhani", name: "Modhani", count: 1 },
  { id: "shana", name: "Shana", count: 1 },
  { id: "verka", name: "Verka", count: 1 },
  { id: "golden-temple", name: "Golden Temple", count: 1 },
  { id: "haldirams", name: "Haldiram's", count: 1 },
  { id: "nanak", name: "Nanak", count: 2 },
  { id: "yfm", name: "Your Fresh Market", count: 1 },
  { id: "sealtest", name: "Sealtest", count: 1 },
  { id: "simply", name: "Simply", count: 1 },
  { id: "wellcare", name: "WellCare", count: 3 },
  { id: "voltx", name: "VoltX", count: 3 },
  { id: "urbanthread", name: "Urban Thread", count: 3 },
  { id: "homeco", name: "HomeCo", count: 3 },
  { id: "pawpal", name: "PawPal", count: 3 },
  { id: "littleone", name: "Little One", count: 3 },
  { id: "glowbe", name: "Glowbe", count: 3 },
  { id: "inkwell", name: "Inkwell", count: 3 },
];

export const productColors = [
  { id: "green", name: "Green", swatch: "#4d8b3f", count: 4 },
  { id: "red", name: "Red", swatch: "#c94a3a", count: 3 },
  { id: "brown", name: "Brown", swatch: "#8a5a3b", count: 3 },
  { id: "blue", name: "Blue", swatch: "#3b6fa0", count: 2 },
  { id: "gray", name: "Gray", swatch: "#8a8a8a", count: 2 },
  { id: "black", name: "Black", swatch: "#111111", count: 2 },
];

// Local produce/staple photos, served from public/product-images/.
const png = (name: string) => `/product-images/ing-${name.toLowerCase().replace(/ /g, "-")}.png`;

export const products: Product[] = [
  {
    id: "am-bananas",
    name: "Organic Bananas, 1.1 lb Bunch",
    categoryId: "fruits-veg",
    brandId: "harvest",
    price: 107,
    compareAtPrice: 126,
    unit: "1.1 lb bunch",
    description: "Naturally ripened, thick-skinned bananas from small-batch growers.",
    image: png("Banana"),
    tag: "Peak season",
    badge: "organic",
    rating: 4.6,
    reviewCount: 128,
    color: "green",
    inStock: true,
    seller_id: "green-basket",
    store_name: "Green Basket",
  },
  {
    id: "am-tomatoes",
    name: "Vine Tomatoes, 1.1 lb",
    categoryId: "fruits-veg",
    brandId: "harvest",
    price: 207,
    compareAtPrice: 244,
    unit: "1.1 lb",
    description: "Juicy tomatoes ripened on the vine. Perfect for salads and slow-cooked curries.",
    image: png("Tomatoes"),
    rating: 4.4,
    reviewCount: 82,
    color: "red",
    inStock: true,
    seller_id: "green-basket",
    store_name: "Green Basket",
  },
  {
    id: "am-spinach",
    name: "Baby Spinach, Triple-Washed",
    categoryId: "fruits-veg",
    brandId: "orchard",
    price: 248,
    unit: "0.4 lb pack",
    description: "Tender, triple-washed baby spinach. Ready to eat right out of the bag.",
    image: png("Spinach"),
    badge: "organic",
    rating: 4.2,
    reviewCount: 44,
    color: "green",
    inStock: true,
    seller_id: "green-basket",
    store_name: "Green Basket",
  },
  {
    id: "am-avocado",
    name: "Hass Avocados, Ready to Eat",
    categoryId: "fruits-veg",
    brandId: "orchard",
    price: 248,
    compareAtPrice: 293,
    unit: "2 pcs",
    description: "Buttery, ripe-when-you-are Hass avocados. Sourced weekly.",
    image: png("Avocado"),
    tag: "Ready to eat",
    rating: 4.7,
    reviewCount: 210,
    color: "green",
    inStock: true,
    seller_id: "green-basket",
    store_name: "Green Basket",
  },
  {
    id: "am-rice",
    name: "Aged Basmati Rice, 2.2 lb",
    categoryId: "grocery-staples",
    brandId: "millhouse",
    price: 497,
    compareAtPrice: 587,
    unit: "2.2 lb",
    description: "Two-year aged long-grain basmati. Fluffs up beautifully every time.",
    image: png("Basmati Rice"),
    rating: 4.8,
    reviewCount: 342,
    color: "brown",
    inStock: true,
    seller_id: "freshmart-grocery",
    store_name: "FreshMart Grocery",
  },
  {
    id: "am-oil",
    name: "Cold-Pressed Mustard Oil, 1 L",
    categoryId: "grocery-staples",
    brandId: "millhouse",
    price: 580,
    compareAtPrice: 684,
    unit: "1 L bottle",
    description: "Cold-pressed, unrefined mustard oil. Bold flavour, rich colour.",
    image: png("Olive Oil"),
    rating: 4.5,
    reviewCount: 95,
    color: "brown",
    inStock: true,
    seller_id: "spice-hub",
    store_name: "Spice Hub",
  },
  {
    id: "am-lentils",
    name: "Red Lentils, Stone-Cleaned 1.1 lb",
    categoryId: "grocery-staples",
    brandId: "millhouse",
    price: 232,
    unit: "1.1 lb",
    description: "Split red lentils, sorted and stone-cleaned. Cook in under 20 minutes.",
    image: png("Red Lentils"),
    rating: 4.3,
    reviewCount: 61,
    color: "red",
    inStock: true,
    seller_id: "freshmart-grocery",
    store_name: "FreshMart Grocery",
  },
  {
    id: "am-milk",
    name: "Farm Fresh Whole Milk, 1 L",
    categoryId: "breakfast-dairy",
    brandId: "daily",
    price: 207,
    unit: "1 L",
    description: "A2 whole milk, pasteurised and bottled within hours of milking.",
    image: png("Milk"),
    badge: "cold_sale",
    rating: 4.6,
    reviewCount: 178,
    color: "gray",
    inStock: true,
    seller_id: "daily-dairy",
    store_name: "Daily Dairy",
  },
  {
    id: "am-eggs",
    name: "Brown Farm Eggs, Pack of 12",
    categoryId: "breakfast-dairy",
    brandId: "daily",
    price: 331,
    compareAtPrice: 391,
    unit: "12 pcs",
    description: "Free-range brown eggs from small farms. Deep-orange yolks, thick whites.",
    image: png("Eggs"),
    tag: "Best seller",
    badge: "bestseller",
    rating: 4.9,
    reviewCount: 512,
    color: "brown",
    inStock: true,
    seller_id: "daily-dairy",
    store_name: "Daily Dairy",
  },
  {
    id: "am-yogurt",
    name: "Greek Yogurt, High Protein",
    categoryId: "breakfast-dairy",
    brandId: "daily",
    price: 165,
    unit: "0.4 lb",
    description: "Thick, strained yogurt with 10 g protein per serving. No added sugar.",
    image: png("Yogurt"),
    badge: "cold_sale",
    rating: 4.4,
    reviewCount: 88,
    color: "gray",
    inStock: true,
    seller_id: "daily-dairy",
    store_name: "Daily Dairy",
  },
  {
    id: "am-granola",
    name: "Honey Almond Granola, 0.7 lb",
    categoryId: "biscuits-snacks",
    brandId: "kitchen",
    price: 456,
    compareAtPrice: 538,
    unit: "0.7 lb",
    description: "Slow-baked oats with real honey and roasted almonds. No refined sugar.",
    image: png("Oats"),
    rating: 4.5,
    reviewCount: 76,
    color: "brown",
    inStock: true,
    seller_id: "quickbites-cafe",
    store_name: "QuickBites Cafe",
  },
  {
    id: "am-chips",
    name: "Kettle Chips, Sea Salt 0.3 lb",
    categoryId: "biscuits-snacks",
    brandId: "kitchen",
    price: 290,
    compareAtPrice: 342,
    unit: "0.3 lb",
    description: "Hand-cooked in small batches. Extra crunch, just the right salt.",
    image: png("Potatoes"),
    rating: 4.3,
    reviewCount: 54,
    color: "black",
    inStock: true,
    seller_id: "quickbites-cafe",
    store_name: "QuickBites Cafe",
  },
  {
    id: "am-bread",
    name: "Artisan Sourdough Loaf, 1 lb",
    categoryId: "breads-bakery",
    brandId: "harvest",
    price: 373,
    compareAtPrice: 440,
    unit: "1 lb loaf",
    description: "Naturally leavened, 24-hour ferment. Crisp crust, open crumb.",
    image: png("Bread"),
    rating: 4.8,
    reviewCount: 187,
    color: "brown",
    inStock: true,
    seller_id: "bake-bliss",
    store_name: "Bake Bliss",
  },
  {
    id: "am-honey",
    name: "Wildflower Honey, 0.6 lb Jar",
    categoryId: "grocery-staples",
    brandId: "orchard",
    price: 663,
    unit: "0.6 lb jar",
    description: "Raw, unfiltered honey from local wildflower meadows. Floral and mellow.",
    image: png("Honey"),
    badge: "organic",
    rating: 4.6,
    reviewCount: 71,
    color: "brown",
    inStock: false,
    seller_id: "organic-harvest",
    store_name: "Organic Harvest",
  },
  // --- Specialty grocery staples (client sample list). Images are placeholders;
  // swap in high-res brand photos when the asset drop lands. ---
  {
    id: "in-daawat",
    name: "Daawat Basmati Rice, 5 lb",
    categoryId: "grocery-staples",
    brandId: "daawat",
    price: 1078,
    compareAtPrice: 1272,
    unit: "5 lb bag",
    description: "Extra-long aged basmati grains that cook up fluffy and separate every time.",
    image: png("Basmati Rice"),
    tag: "Aged 2 years",
    rating: 4.8,
    reviewCount: 318,
    color: "brown",
    inStock: true,
    seller_id: "spice-hub",
    store_name: "Spice Hub",
  },
  {
    id: "in-srikhand",
    name: "Amul Elaichi Srikhand",
    categoryId: "breakfast-dairy",
    brandId: "amul",
    price: 373,
    unit: "0.9 lb tub",
    description: "Rich, creamy strained-yogurt dessert with cardamom. Chilled and ready to serve.",
    image: png("Yogurt"),
    badge: "cold_sale",
    rating: 4.6,
    reviewCount: 142,
    color: "gray",
    inStock: true,
    seller_id: "daily-dairy",
    store_name: "Daily Dairy",
  },
  {
    id: "in-vadilal",
    name: "Vadilal Frozen Green Peas, 1.1 lb",
    categoryId: "frozen",
    brandId: "vadilal",
    price: 290,
    compareAtPrice: 342,
    unit: "1.1 lb pack",
    description: "Individually quick-frozen green peas, sweet and ready for any curry or pulao.",
    image: png("Peas"),
    rating: 4.4,
    reviewCount: 87,
    color: "green",
    inStock: true,
    seller_id: "spice-hub",
    store_name: "Spice Hub",
  },
  {
    id: "in-roma",
    name: "Roma Tomatoes, 1.1 lb",
    categoryId: "fruits-veg",
    brandId: "harvest",
    price: 190,
    compareAtPrice: 224,
    unit: "1.1 lb",
    description: "Firm, meaty Roma tomatoes — low on seeds, perfect for sauces and curries.",
    image: png("Tomatoes"),
    tag: "Sauce-ready",
    rating: 4.5,
    reviewCount: 96,
    color: "red",
    inStock: true,
    seller_id: "green-basket",
    store_name: "Green Basket",
  },
  {
    id: "in-rusk",
    name: "Britannia Premium Rusk, 0.9 lb",
    categoryId: "biscuits-snacks",
    brandId: "britannia",
    price: 273,
    unit: "0.9 lb pack",
    description: "Crisp, twice-baked wheat rusk — the classic companion for tea and coffee.",
    image: png("Bread"),
    rating: 4.5,
    reviewCount: 118,
    color: "brown",
    inStock: true,
    seller_id: "spice-hub",
    store_name: "Spice Hub",
  },
  {
    id: "in-goodday",
    name: "Britannia Good Day Cashew Cookies, 0.5 lb",
    categoryId: "biscuits-snacks",
    brandId: "britannia",
    price: 248,
    compareAtPrice: 293,
    unit: "0.5 lb pack",
    description: "Buttery cashew cookies with a rich crunch. A lunchbox and tea-time favourite.",
    image: png("Butter"),
    tag: "Best seller",
    badge: "bestseller",
    rating: 4.7,
    reviewCount: 231,
    color: "brown",
    inStock: true,
    seller_id: "spice-hub",
    store_name: "Spice Hub",
  },
  // --- Real Canadian retail catalogue (verified names, sizes, SKUs and
  // clean-background product images from retailer CDNs). ---
  {
    id: "ca-hellmanns-mayo",
    name: "Hellmann's Real Mayonnaise, 445 mL",
    categoryId: "grocery-staples",
    brandId: "hellmanns",
    price: 549,
    compareAtPrice: 649,
    unit: "445 mL jar",
    description:
      "Creamy, made-with-real-eggs mayonnaise — a fridge-door staple for every sandwich.",
    image: "/product-images/ca-hellmanns-mayo.jpg",
    rating: 4.7,
    reviewCount: 184,
    inStock: true,
    seller_id: "freshmart-grocery",
    store_name: "FreshMart Grocery",
  },
  {
    id: "ca-modhani-dahi",
    name: "Modhani Authentic 3.2% Dahi, 4.4 lb",
    categoryId: "breakfast-dairy",
    brandId: "modhani",
    price: 699,
    unit: "4.4 lb tub",
    description: "Thick, authentic 3.2% M.F. plain yogurt (dahi) set the traditional way.",
    image: "/product-images/ca-modhani-dahi.jpg",
    badge: "cold_sale",
    rating: 4.6,
    reviewCount: 92,
    inStock: true,
    seller_id: "daily-dairy",
    store_name: "Daily Dairy",
  },
  {
    id: "ca-shana-paratha",
    name: "Shana Plain Lacha Paratha, 5 Pack",
    categoryId: "frozen",
    brandId: "shana",
    price: 449,
    compareAtPrice: 519,
    unit: "0.9 lb, 5-pack",
    description: "Flaky, layered frozen lacha paratha — straight from freezer to hot tawa.",
    image: "/product-images/ca-shana-paratha.jpg",
    rating: 4.5,
    reviewCount: 137,
    inStock: true,
    seller_id: "spice-hub",
    store_name: "Spice Hub",
  },
  {
    id: "ca-verka-rusk",
    name: "Verka Eggless Suji Rusk, 0.8 lb",
    categoryId: "biscuits-snacks",
    brandId: "verka",
    price: 299,
    unit: "0.8 lb box",
    description: "Crisp eggless semolina toast — the classic tea-time and coffee companion.",
    image: "/product-images/ca-verka-rusk.jpg",
    rating: 4.4,
    reviewCount: 68,
    color: "brown",
    inStock: true,
    seller_id: "spice-hub",
    store_name: "Spice Hub",
  },
  {
    id: "ca-golden-temple-atta",
    name: "Golden Temple Durum Atta Flour Blend, 20 lb",
    categoryId: "grocery-staples",
    brandId: "golden-temple",
    price: 1499,
    compareAtPrice: 1699,
    unit: "20 lb bag",
    description: "Durum wheat atta blend for soft rotis and parathas — bulk value for the pantry.",
    image: "/product-images/ca-golden-temple-atta.jpg",
    tag: "Bulk value",
    rating: 4.7,
    reviewCount: 221,
    color: "brown",
    inStock: true,
    seller_id: "spice-hub",
    store_name: "Spice Hub",
  },
  {
    id: "ca-haldirams-boondi",
    name: "Haldiram's Nagpur Boondi, 0.8 lb",
    categoryId: "biscuits-snacks",
    brandId: "haldirams",
    price: 249,
    unit: "0.8 lb bag",
    description: "Crunchy Nagpur-style gram-flour boondi — snack as-is or turn into raita.",
    image: "/product-images/ca-haldirams-boondi.jpg",
    rating: 4.6,
    reviewCount: 156,
    inStock: true,
    seller_id: "spice-hub",
    store_name: "Spice Hub",
  },
  {
    id: "ca-aashirvaad-atta",
    name: "Aashirvaad Whole Wheat Flour (Atta), 20 lb",
    categoryId: "grocery-staples",
    brandId: "aashirvaad",
    price: 1549,
    compareAtPrice: 1749,
    unit: "20 lb bag",
    description: "100% whole wheat atta, stone-ground for soft, everyday rotis and parathas.",
    image: "/product-images/ca-aashirvaad-atta.jpg",
    tag: "Everyday staple",
    rating: 4.8,
    reviewCount: 342,
    color: "brown",
    inStock: true,
    seller_id: "spice-hub",
    store_name: "Spice Hub",
  },
  {
    id: "ca-nanak-paneer",
    name: "Nanak Paneer, 3.5 lb",
    categoryId: "breakfast-dairy",
    brandId: "nanak",
    price: 1299,
    unit: "3.5 lb block",
    description: "Fresh, firm 100% vegetarian paneer — cubes up perfectly for curries and grills.",
    image: "/product-images/ca-nanak-paneer.jpg",
    rating: 4.7,
    reviewCount: 203,
    inStock: true,
    seller_id: "daily-dairy",
    store_name: "Daily Dairy",
  },
  {
    id: "ca-nanak-kebab",
    name: "Nanak Hara Bhara Kebab, 1.3 lb",
    categoryId: "frozen",
    brandId: "nanak",
    price: 549,
    compareAtPrice: 629,
    unit: "1.3 lb box (~35 pcs)",
    description: "Spinach-and-pea veggie kebabs, ready to pan-fry — about 35 pieces per box.",
    image: "/product-images/ca-nanak-kebab.jpg",
    badge: "bestseller",
    rating: 4.5,
    reviewCount: 118,
    color: "green",
    inStock: true,
    seller_id: "spice-hub",
    store_name: "Spice Hub",
  },
  {
    id: "ca-yfm-spinach-dip",
    name: "Your Fresh Market Spinach Dip, 0.5 lb",
    categoryId: "grocery-staples",
    brandId: "yfm",
    price: 399,
    unit: "0.5 lb tub",
    description: "Cool, creamy spinach dip — ready to serve with bread bowls, chips or crudités.",
    image: "/product-images/ca-yfm-spinach-dip.jpg",
    badge: "cold_sale",
    rating: 4.4,
    reviewCount: 57,
    color: "green",
    inStock: true,
    seller_id: "freshmart-grocery",
    store_name: "FreshMart Grocery",
  },
  {
    id: "ca-sealtest-milk",
    name: "Sealtest 6% M.F. Milk, 4 L",
    categoryId: "breakfast-dairy",
    brandId: "sealtest",
    price: 549,
    unit: "4 L bag (3-pack)",
    description: "Rich 6% M.F. bagged milk — three pouches, cold-chain fresh for the whole week.",
    image: "/product-images/ca-sealtest-milk.jpg",
    badge: "cold_sale",
    rating: 4.6,
    reviewCount: 149,
    color: "blue",
    inStock: true,
    seller_id: "daily-dairy",
    store_name: "Daily Dairy",
  },
  {
    id: "ca-simply-lemonade",
    name: "Simply Lemonade with Raspberry, 1.54 L",
    categoryId: "beverages",
    brandId: "simply",
    price: 449,
    compareAtPrice: 499,
    unit: "1.54 L bottle",
    description: "All-natural lemonade with a burst of raspberry — no added colours or flavours.",
    image: "/product-images/ca-simply-lemonade.jpg",
    tag: "Chilled",
    rating: 4.6,
    reviewCount: 96,
    color: "red",
    inStock: true,
    seller_id: "quickbites-cafe",
    store_name: "QuickBites Cafe",
  },

  // --- Non-grocery store catalogue (labeled placeholder images until real
  // product photos are supplied). ---
  {
    id: "rx-ibuprofen",
    name: "Ibuprofen Pain Relief 200mg, 50 Caplets",
    categoryId: "healthcare",
    brandId: "wellcare",
    price: 746,
    unit: "50 caplets",
    description: "Fast-acting ibuprofen for headaches, aches and fever.",
    image: "/product-images/rx-ibuprofen.jpg",
    rating: 4.6,
    reviewCount: 88,
    inStock: true,
    seller_id: "medicare-pharmacy",
    store_name: "MediCare Pharmacy",
  },
  {
    id: "rx-multivitamin",
    name: "Daily Multivitamin, 90 Tablets",
    categoryId: "healthcare",
    brandId: "wellcare",
    price: 1078,
    unit: "90 tablets",
    description: "Complete A-to-Zinc daily multivitamin for everyday wellness.",
    image: "/product-images/rx-multivitamin.jpg",
    rating: 4.5,
    reviewCount: 142,
    inStock: true,
    seller_id: "medicare-pharmacy",
    store_name: "MediCare Pharmacy",
  },
  {
    id: "rx-bandages",
    name: "First-Aid Bandages, 40 Count",
    categoryId: "healthcare",
    brandId: "wellcare",
    price: 373,
    unit: "40 ct",
    description: "Flexible fabric bandages in assorted sizes for everyday cuts.",
    image: "/product-images/rx-bandages.jpg",
    rating: 4.4,
    reviewCount: 61,
    inStock: true,
    seller_id: "medicare-pharmacy",
    store_name: "MediCare Pharmacy",
  },
  {
    id: "el-earbuds",
    name: "Wireless Earbuds",
    categoryId: "electronics",
    brandId: "voltx",
    price: 3319,
    compareAtPrice: 3899,
    unit: "1 pair",
    description: "True-wireless earbuds with charging case and 24-hour battery.",
    image: "/product-images/el-earbuds.jpg",
    rating: 4.4,
    reviewCount: 274,
    color: "black",
    inStock: true,
    seller_id: "smart-electronics",
    store_name: "Smart Electronics",
  },
  {
    id: "el-charger",
    name: "USB-C Fast Charger 30W",
    categoryId: "electronics",
    brandId: "voltx",
    price: 1659,
    unit: "1 adapter",
    description: "Compact 30W USB-C wall charger for phones and tablets.",
    image: "/product-images/el-charger.jpg",
    rating: 4.5,
    reviewCount: 118,
    inStock: true,
    seller_id: "smart-electronics",
    store_name: "Smart Electronics",
  },
  {
    id: "el-powerbank",
    name: "Power Bank 10000mAh",
    categoryId: "electronics",
    brandId: "voltx",
    price: 2489,
    compareAtPrice: 2899,
    unit: "1 unit",
    description: "Slim 10000mAh power bank with dual USB output.",
    image: "/product-images/el-powerbank.jpg",
    rating: 4.6,
    reviewCount: 203,
    color: "black",
    inStock: true,
    seller_id: "smart-electronics",
    store_name: "Smart Electronics",
  },
  {
    id: "fa-tee",
    name: "Cotton Crew T-Shirt",
    categoryId: "fashion",
    brandId: "urbanthread",
    price: 1244,
    unit: "1 piece",
    description: "Soft mid-weight combed-cotton crew tee. Everyday staple.",
    image: "/product-images/fa-tee.jpg",
    rating: 4.5,
    reviewCount: 96,
    color: "blue",
    inStock: true,
    seller_id: "fashion-avenue",
    store_name: "Fashion Avenue",
  },
  {
    id: "fa-socks",
    name: "Ankle Socks, 5-Pack",
    categoryId: "fashion",
    brandId: "urbanthread",
    price: 829,
    unit: "5 pairs",
    description: "Cushioned cotton-blend ankle socks. Breathable all day.",
    image: "/product-images/fa-socks.jpg",
    rating: 4.4,
    reviewCount: 74,
    inStock: true,
    seller_id: "fashion-avenue",
    store_name: "Fashion Avenue",
  },
  {
    id: "fa-tote",
    name: "Canvas Tote Bag",
    categoryId: "fashion",
    brandId: "urbanthread",
    price: 1078,
    unit: "1 bag",
    description: "Sturdy reusable canvas tote for groceries and errands.",
    image: "/product-images/fa-tote.jpg",
    rating: 4.6,
    reviewCount: 131,
    color: "green",
    inStock: true,
    seller_id: "fashion-avenue",
    store_name: "Fashion Avenue",
  },
  {
    id: "hm-dishsoap",
    name: "Dish Soap, 740 mL",
    categoryId: "household",
    brandId: "homeco",
    price: 290,
    compareAtPrice: 342,
    unit: "740 mL bottle",
    description: "Grease-cutting dish soap with a fresh citrus scent.",
    image: "/product-images/hm-dishsoap.jpg",
    rating: 4.5,
    reviewCount: 156,
    inStock: true,
    seller_id: "home-essentials",
    store_name: "Home Essentials",
  },
  {
    id: "hm-bins",
    name: "Storage Bins, Set of 3",
    categoryId: "household",
    brandId: "homeco",
    price: 1410,
    unit: "set of 3",
    description: "Stackable storage bins to tidy shelves, closets and pantry.",
    image: "/product-images/hm-bins.jpg",
    rating: 4.4,
    reviewCount: 82,
    inStock: true,
    seller_id: "home-essentials",
    store_name: "Home Essentials",
  },
  {
    id: "hm-towels",
    name: "Kitchen Towels, 4-Pack",
    categoryId: "household",
    brandId: "homeco",
    price: 746,
    unit: "4-pack",
    description: "Absorbent cotton kitchen towels for everyday cleanup.",
    image: "/product-images/hm-towels.jpg",
    rating: 4.5,
    reviewCount: 67,
    inStock: true,
    seller_id: "home-essentials",
    store_name: "Home Essentials",
  },
  {
    id: "pet-dogfood",
    name: "Dry Dog Food, 7 lb",
    categoryId: "pet-supplies",
    brandId: "pawpal",
    price: 1576,
    compareAtPrice: 1849,
    unit: "7 lb bag",
    description: "Chicken-and-rice complete dry food for adult dogs.",
    image: "/product-images/pet-dogfood.jpg",
    rating: 4.6,
    reviewCount: 221,
    color: "brown",
    inStock: true,
    seller_id: "pet-paradise",
    store_name: "Pet Paradise",
  },
  {
    id: "pet-cattreats",
    name: "Cat Treats, Salmon 6 oz",
    categoryId: "pet-supplies",
    brandId: "pawpal",
    price: 414,
    unit: "6 oz pack",
    description: "Grain-free salmon treats cats love. Great for training.",
    image: "/product-images/pet-cattreats.jpg",
    rating: 4.5,
    reviewCount: 98,
    inStock: true,
    seller_id: "pet-paradise",
    store_name: "Pet Paradise",
  },
  {
    id: "pet-litter",
    name: "Clumping Cat Litter, 14 lb",
    categoryId: "pet-supplies",
    brandId: "pawpal",
    price: 995,
    unit: "14 lb bag",
    description: "Low-dust clumping clay litter with fast odour control.",
    image: "/product-images/pet-litter.jpg",
    rating: 4.4,
    reviewCount: 143,
    inStock: true,
    seller_id: "pet-paradise",
    store_name: "Pet Paradise",
  },
  {
    id: "bb-wipes",
    name: "Baby Wipes, 216 Count",
    categoryId: "baby",
    brandId: "littleone",
    price: 829,
    compareAtPrice: 979,
    unit: "216 ct",
    description: "Fragrance-free, hypoallergenic wipes gentle on baby skin.",
    image: "/product-images/bb-wipes.jpg",
    rating: 4.7,
    reviewCount: 312,
    inStock: true,
    seller_id: "baby-care-world",
    store_name: "Baby Care World",
  },
  {
    id: "bb-diapers",
    name: "Diapers Size 3, 78 Count",
    categoryId: "baby",
    brandId: "littleone",
    price: 2074,
    unit: "78 ct",
    description: "Ultra-absorbent diapers with a soft, breathable fit.",
    image: "/product-images/bb-diapers.jpg",
    rating: 4.6,
    reviewCount: 264,
    inStock: true,
    seller_id: "baby-care-world",
    store_name: "Baby Care World",
  },
  {
    id: "bb-lotion",
    name: "Baby Lotion, 300 mL",
    categoryId: "baby",
    brandId: "littleone",
    price: 580,
    unit: "300 mL bottle",
    description: "Gentle daily moisturizing lotion for delicate skin.",
    image: "/product-images/bb-lotion.jpg",
    rating: 4.5,
    reviewCount: 118,
    inStock: true,
    seller_id: "baby-care-world",
    store_name: "Baby Care World",
  },
  {
    id: "bu-facewash",
    name: "Gentle Face Wash, 150 mL",
    categoryId: "beauty",
    brandId: "glowbe",
    price: 829,
    unit: "150 mL tube",
    description: "Soap-free gel cleanser for a soft, fresh, non-tight feel.",
    image: "/product-images/bu-facewash.jpg",
    rating: 4.5,
    reviewCount: 137,
    inStock: true,
    seller_id: "beauty-bloom",
    store_name: "Beauty Bloom",
  },
  {
    id: "bu-lipbalm",
    name: "Lip Balm, 3-Pack",
    categoryId: "beauty",
    brandId: "glowbe",
    price: 497,
    unit: "3-pack",
    description: "Nourishing beeswax lip balm trio for smooth, soft lips.",
    image: "/product-images/bu-lipbalm.jpg",
    rating: 4.6,
    reviewCount: 92,
    inStock: true,
    seller_id: "beauty-bloom",
    store_name: "Beauty Bloom",
  },
  {
    id: "bu-serum",
    name: "Vitamin C Serum, 30 mL",
    categoryId: "beauty",
    brandId: "glowbe",
    price: 1576,
    compareAtPrice: 1849,
    unit: "30 mL bottle",
    description: "Brightening vitamin C serum for a healthy daily glow.",
    image: "/product-images/bu-serum.jpg",
    rating: 4.5,
    reviewCount: 174,
    inStock: true,
    seller_id: "beauty-bloom",
    store_name: "Beauty Bloom",
  },
  {
    id: "st-notebook",
    name: "A5 Ruled Notebook, 2-Pack",
    categoryId: "stationery",
    brandId: "inkwell",
    price: 663,
    unit: "2-pack",
    description: "Sturdy A5 ruled notebooks with smooth 80gsm paper.",
    image: "/product-images/st-notebook.jpg",
    rating: 4.5,
    reviewCount: 78,
    inStock: true,
    seller_id: "stationery-point",
    store_name: "Stationery Point",
  },
  {
    id: "st-pens",
    name: "Gel Pens, 10-Pack",
    categoryId: "stationery",
    brandId: "inkwell",
    price: 539,
    unit: "10-pack",
    description: "Smooth-writing 0.5mm gel pens in assorted colours.",
    image: "/product-images/st-pens.jpg",
    rating: 4.6,
    reviewCount: 121,
    inStock: true,
    seller_id: "stationery-point",
    store_name: "Stationery Point",
  },
  {
    id: "st-stickies",
    name: "Sticky Notes, 12 Pads",
    categoryId: "stationery",
    brandId: "inkwell",
    price: 456,
    unit: "12 pads",
    description: "Bright repositionable sticky notes for reminders and tabs.",
    image: "/product-images/st-stickies.jpg",
    rating: 4.4,
    reviewCount: 64,
    color: "green",
    inStock: true,
    seller_id: "stationery-point",
    store_name: "Stationery Point",
  },
];

export function getProduct(id: string) {
  return products.find((p) => p.id === id);
}

export function productsByCategory(categoryId: string) {
  return products.filter((p) => p.categoryId === categoryId);
}

export function getStoreBySlug(slug: string) {
  return stores.find((v) => v.slug === slug);
}

export function productsByStore(storeId: string) {
  return products.filter((p) => p.seller_id === storeId);
}

export function storesByCategory(categoryId: string) {
  return stores.filter((v) => v.categoryId === categoryId);
}

export function discountPct(p: Product) {
  if (!p.compareAtPrice || p.compareAtPrice <= p.price) return 0;
  return Math.round(((p.compareAtPrice - p.price) / p.compareAtPrice) * 100);
}

export type OrderStatus = "placed" | "packed" | "out_for_delivery" | "delivered";

export type Order = {
  id: string;
  placedAt: string;
  items: { productId: string; qty: number; price: number }[];
  subtotal: number;
  delivery: number;
  total: number;
  status: OrderStatus;
  etaMinutes?: number;
  address: string;
};

export const pastOrders: Order[] = [
  {
    id: "AM-9402",
    placedAt: "2026-07-04T10:12:00Z",
    items: [
      { productId: "am-bananas", qty: 2, price: 79 },
      { productId: "am-bread", qty: 1, price: 180 },
      { productId: "am-milk", qty: 2, price: 68 },
    ],
    subtotal: 474,
    delivery: 0,
    total: 474,
    status: "out_for_delivery",
    etaMinutes: 14,
    address: "21 Queen Mary Drive, Brampton ON L7A 1X7",
  },
  {
    id: "AM-8829",
    placedAt: "2026-07-01T18:40:00Z",
    items: [
      { productId: "am-avocado", qty: 1, price: 199 },
      { productId: "am-tomatoes", qty: 2, price: 64 },
    ],
    subtotal: 327,
    delivery: 29,
    total: 356,
    status: "delivered",
    address: "21 Queen Mary Drive, Brampton ON L7A 1X7",
  },
  {
    id: "AM-8551",
    placedAt: "2026-06-24T09:05:00Z",
    items: [
      { productId: "am-rice", qty: 1, price: 349 },
      { productId: "am-lentils", qty: 2, price: 129 },
      { productId: "am-oil", qty: 1, price: 285 },
    ],
    subtotal: 892,
    delivery: 0,
    total: 892,
    status: "delivered",
    address: "21 Queen Mary Drive, Brampton ON L7A 1X7",
  },
];
